warungApp:
  name: "Warung Makan Bahari"
  api:
    url: "localhost:1234"
    log_level: "debug"
    group: "api"
  db:
    host: "localhost"
    port: "5432"
    user: "postgres"
    password: "tinoganteng21"
    name: "warteg_bahari"